### ISSUE TITLE
Space between words

### ISSUE THREAD

**Issue by dbojan** [zh-h/Windows.Media.Ocr.Cli#1]
Hi.
Currently there are no spaces between words so
"This is a test" becomes "Thisisatest".
Please add a space between words.

Thanks.

**Comment by zh-h** [comment]
@dbojan Emmm, those feature are provided by the Windows.Media.Ocr libs. I am powerless to fixing it, But you can put your pictures onto there and then try again with different image 
adjust parameters (contrast ratio)

**Comment by dbojan** [comment]
Hi.
Thanks for your  answer.

I am talking about something similar to: https://blogs.windows.com/buildingapps/2014/09/18/microsoft-ocr-library-for-windows-runtime/

In your Program.cs, line 103:
line += word.Text;
maybe replace something like
line += word.Text + " ";

Thanks,

**Comment by zh-h** [comment]
@dbojan I am a Chinese character user, so I removed the spaces between the words. It turns out that this affects the recognition of English sentences.

**Comment by dbojan** [comment]
Thanks for the merge.
Please build binary if possible.

BR,

**Comment by zh-h** [comment]
@dbojan https://github.com/zh-h/Windows.Media.Ocr.Cli/releases/tag/v0.2.0 done
