### ISSUE TITLE
命名空间“Windows”中不存在类型或命名空间名“Graphics”

### ISSUE THREAD

**Issue by pengyuwei** [zh-h/Windows.Media.Ocr.Cli#3]
使用VS 2017编译工程，提示如下错误：

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Windows”中不存在类型或命名空间名“Graphics”(是否缺少程序集引用?)	Windows.Media.Ocr.Cli	D:\Project\Ocr\Windows.Media.Ocr.Cli\Program.cs	15	活动的
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Windows”中不存在类型或命名空间名“Storage”(是否缺少程序集引用?)	Windows.Media.Ocr.Cli	D:\Project\Ocr\Windows.Media.Ocr.Cli\Program.cs	16	活动的
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0103	当前上下文中不存在名称“OcrEngine”	Windows.Media.Ocr.Cli	D:\Project\Ocr\Windows.Media.Ocr.Cli\Program.cs	36	活动的

**Comment by zh-h** [comment]
需要引入本地Windows 10 SDK
